[package]
name = "nanodhcp"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
description = "Minimal DHCPv4 server for homelab / embedded Linux / appliance OS"
repository = ""
readme = "README.md"

[[bin]]
name = "nanodhcp"
path = "src/main.rs"

# No external dependencies by design (std only).

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
